### ISSUE TITLE
Set up GitHub Actions for automated testing and CI/CD

### ISSUE THREAD

**Issue by sean-roth** [sean-roth/compel-english#10]
## Overview
Set up GitHub Actions to automatically run tests whenever code is pushed, ensuring quality control and enabling automated feedback for Claude Code implementations.

### 1. Basic Test Workflow
Create `.github/workflows/tests.yml`:

```yaml
name: Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: testing
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, dom, fileinfo, mysql
        coverage: none

    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    
    - name: Generate key
      run: php artisan key:generate
    
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    
    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite
    
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: vendor/bin/phpunit
    
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        
    - name: Install Node dependencies
      run: npm ci
      
    - name: Build assets
      run: npm run build
      
    - name: Run TypeScript checks
      run: npm run types
      
    - name: Run ESLint
      run: npm run lint
```

### 2. Code Quality Workflow
Create `.github/workflows/code-quality.yml`:

```yaml
name: Code Quality

on: [push, pull_request]

jobs:
  phpstan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      
    - name: Run PHPStan
      run: vendor/bin/phpstan analyse --error-format=github
      
  pint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      
    - name: Run Laravel Pint
      run: vendor/bin/pint --test
```

### 3. Auto-Deploy Workflow (if tests pass)
Create `.github/workflows/deploy.yml`:

```yaml
name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  test:
    uses: ./.github/workflows/tests.yml
    
  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: success()
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy to Cloud Run
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      run: |
        echo "$GOOGLE_CREDENTIALS" > /tmp/gcp-key.json
        gcloud auth activate-service-account --key-file=/tmp/gcp-key.json
        gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT }}/compel-english
        gcloud run deploy compel-english \
          --image gcr.io/${{ secrets.GCP_PROJECT }}/compel-english \
          --platform managed \
          --region us-central1
```

### 4. Add Status Badge to README
```markdown
![Tests](https://github.com/sean-roth/compel-english/workflows/Tests/badge.svg)
![Code Quality](https://github.com/sean-roth/compel-english/workflows/Code%20Quality/badge.svg)
```

### 5. Branch Protection Rules
In GitHub repository settings:
- Require status checks to pass before merging
- Require branches to be up to date before merging
- Include administrators
- Required status checks: "test", "phpstan", "pint"

### 6. Add PHPStan Configuration
Create `phpstan.neon`:
```neon
parameters:
    level: 5
    paths:
        - app
        - config
        - database
        - routes
        - tests
    ignoreErrors:
        - '#PHPDoc tag @var#'
    checkMissingIterableValueType: false
```

### 7. Add Composer Scripts
Update `composer.json`:
```json
"scripts": {
    "test": "phpunit",
    "test:coverage": "phpunit --coverage-html coverage",
    "analyse": "phpstan analyse",
    "format": "pint",
    "check": [
        "@test",
        "@analyse",
        "@format"
    ]
}
```

## Benefits

1. **Automatic Testing**: Every push triggers tests
2. **Quality Gates**: Code must pass before merging
3. **Visual Feedback**: GitHub shows ✅ or ❌ on commits
4. **Deploy Confidence**: Only tested code deploys
5. **Team Awareness**: Everyone sees test status

### Issue-Triggered Workflows
```yaml
on:
  issues:
    types: [opened, labeled]
    
jobs:
  auto-assign:
    if: contains(github.event.label.name, 'bug')
    runs-on: ubuntu-latest
    steps:
      - name: Assign to bot
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.addAssignees({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              assignees: ['claude-code-bot']
            })
```

### Customer Service Integration
1. CS creates issue with specific labels
2. GitHub Action validates and formats issue
3. Adds to project board
4. Notifies development team
5. Claude Code picks up formatted issues

## Success Criteria
- All workflows pass on main branch
- Tests run in under 3 minutes
- Automatic deployment on success
- Clear feedback in pull requests
- Status badges show current state
